### ISSUE TITLE
Nasty skeletons spawning at light greater than 0, while settings are at 0

### ISSUE THREAD

**Issue by jasoncollege24** [Lupicus/NastyMobs#4]
Minecraft: Java 1.18.2
Modpack: FTB Plexiglass Mountain (played on my personal home server)

So, I've been trying to figure out why nasty skeletons have been spawning so close to my base, which is quite lit up, and figured they were just wandering in from beyond the perimeter... that is, until I made a cow farm...

Inside the cow farm, there is a single torch. The light level inside the farm drops to no lower than 6, yet nasty mobs are still spawning inside the fence.

I checked the config file, which claims the required light levels are supposed to be 0, but it looks like it's being ignored, and using spawn rules from before 1.16

**Comment by Lupicus** [comment]
I've done some initial testing and it seems to be working correctly, but I'll do some more testing.

**Comment by jasoncollege24** [comment]
I could be due to an issue in the modpack. There is another mod in the pack that creates new mobs, and they're doing roughly the same thing.

Edit: I did report this to the modpack creator too.

**Comment by Lupicus** [comment]
I didn't test the mod pack, just this mod and a testing mod. I created 2 identical platforms with one having a torch (light level > 0) and other had light level 0. Mobs including the nasty mobs only spawned on the platform without the torch. So it seems something in the pack is changing the spawning rules for the nasty mobs.

**Comment by Raidobw2** [comment]
Hello! I'm one of the devs for Plexiglass Mountain. We have been using InControl to regulate some mob spawns and difficulty, Nasty Mobs was one of them. Until jasoncollege24 reported this I was not aware that they were spawning in light, and so at first I thought perhaps our use of the "allow" keyword for InControl would do that. I did change this keyword in-dev to "default", which would normally use the mob's normal spawning conditions when spawning them in the world.
![image](https://user-images.githubusercontent.com/17010632/174983294-4ac6fac3-1cf0-44b6-973e-b3eac6af8f4c.png)

However, that did not seem to be the case. I thought I'd then opt out of InControl and let your mod spawn the skeletons itself, but it looks they aren't spawning either. I'm not sure if that could be an interaction with Biomes O Plenty, since it is in the modpack. When doing this test I reverted the config to a default one and checked a minecraft plains biome. I tried applying a glow effect to Nasty Skeletons, but none were detected.

I then ran a test in a small custom 1.18.2 instance without a biome mod, and the Nasty Skeletons indeed were spawning.

I've also tried playing with InControl's light regulation for mob spawning, but the Nasty Skeletons don't seem affected.

As a note, the current configuration in Plexiglass Mountain did change the light level that was written in the Nasty common config, since the original light level 7 is no longer used in 1.18.2. Mobs should only spawn in complete darkness.

I have the feeling this is two issues in one. At the moment I'm unable to "fix" their spawning through any means: either by reverting the Nasty common config/dismantling InControl or by trying to use InControl to regulate light level spawns.
If you'd want me to run some more tests I'll be glad to,

Thanks in advance for your help

**Comment by Lupicus** [comment]
There are 2 light levels in the config to match Minecraft, which still uses 7 for skeletons, but added a block light check which is 0. Changing the 7 to 0 might have them still spawn, but more likely the other monsters will spawn since they use 7, until the cap is reached.
Thanks for the info on the biomes mod, I'll take a look at what is happening.

**Comment by Lupicus** [comment]
I loaded the BiomesOPlenty-1.18.2-16.0.0.134 (latest) and also the mod it needs with nasty mobs and they seem to spawn in those new biomes properly (same as other mobs). I'll downgrade version to match yours and retest things.

**Comment by Raidobw2** [comment]
Thanks for the reply! Hmm that means there might be another one interfering in the pack. There is WYML I think might possibly do something to this. I'll do a binary search and remove mods one at a time until they spawn, I'll put my results here afterwards

**Comment by Lupicus** [comment]
I loaded same version used in pack and also added in control mod. I did no setting changes and nasty mobs spawned correctly in the test biome (biomesoplenty:bayou).

**Comment by Raidobw2** [comment]
I've tested again and reverted the config to 7 for light level, that seemed to have been the issue. Changing it from 0 to 7 fixed the mod's spawning.

I'll let your mod register its spawns and take out the InControl spawning code, that will effectively be a good solution. I'll follow up with the InControl author in any case, that is odd behavior.

You can close this issue, it's resolved. Thanks a lot for your help!
